# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98b236f6e0ed1d022eef9fc4416decd0c6fc92169e5f0e2fe651c4c7625f8ea0b09d8e7b938fc883d58575eb5142d3379f1edb7c24d0903182082b465dd26efe

test:
  secret_key_base: 90800ad7bcc040f1437f37a64ede9aa2c0e9106f65783bf89c7a86c297d7c7768bfd3cc17dbaad7644f18622766f51f38fafb78fc356785b3ebdee5657ac1958

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
